# Generated by Django 5.0.7 on 2024-07-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='produto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='cadastros.categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='cadastros.marcas')),
            ],
        ),
    ]
