# Generated by Django 5.0.7 on 2024-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_clientes_endereco_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
