# Generated by Django 5.0.7 on 2024-07-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_produtos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
