# Generated by Django 5.0.7 on 2024-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_clientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
