# Generated by Django 5.0.7 on 2024-08-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_produtos_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='estoque',
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('data', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protudo', to='cadastros.produtos')),
            ],
        ),
    ]
