# Generated by Django 5.0.7 on 2024-08-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_produtos_estoque_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produtos',
            name='porcentagem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
